/*
 * Giphy API
 * Giphy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@giphy.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GifImagesDownsized;
import com.konfigthis.client.model.GifImagesDownsizedLarge;
import com.konfigthis.client.model.GifImagesDownsizedMedium;
import com.konfigthis.client.model.GifImagesDownsizedSmall;
import com.konfigthis.client.model.GifImagesDownsizedStill;
import com.konfigthis.client.model.GifImagesFixedHeight;
import com.konfigthis.client.model.GifImagesFixedHeightDownsampled;
import com.konfigthis.client.model.GifImagesFixedHeightSmall;
import com.konfigthis.client.model.GifImagesFixedHeightSmallStill;
import com.konfigthis.client.model.GifImagesFixedHeightStill;
import com.konfigthis.client.model.GifImagesFixedWidth;
import com.konfigthis.client.model.GifImagesFixedWidthDownsampled;
import com.konfigthis.client.model.GifImagesFixedWidthSmall;
import com.konfigthis.client.model.GifImagesFixedWidthSmallStill;
import com.konfigthis.client.model.GifImagesFixedWidthStill;
import com.konfigthis.client.model.GifImagesLooping;
import com.konfigthis.client.model.GifImagesOriginal;
import com.konfigthis.client.model.GifImagesOriginalStill;
import com.konfigthis.client.model.GifImagesPreview;
import com.konfigthis.client.model.GifImagesPreviewGif;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GifImages
 */
public class GifImagesTest {
    private final GifImages model = new GifImages();

    /**
     * Model tests for GifImages
     */
    @Test
    public void testGifImages() {
        // TODO: test GifImages
    }

    /**
     * Test the property 'downsized'
     */
    @Test
    public void downsizedTest() {
        // TODO: test downsized
    }

    /**
     * Test the property 'downsizedLarge'
     */
    @Test
    public void downsizedLargeTest() {
        // TODO: test downsizedLarge
    }

    /**
     * Test the property 'downsizedMedium'
     */
    @Test
    public void downsizedMediumTest() {
        // TODO: test downsizedMedium
    }

    /**
     * Test the property 'downsizedSmall'
     */
    @Test
    public void downsizedSmallTest() {
        // TODO: test downsizedSmall
    }

    /**
     * Test the property 'downsizedStill'
     */
    @Test
    public void downsizedStillTest() {
        // TODO: test downsizedStill
    }

    /**
     * Test the property 'fixedHeight'
     */
    @Test
    public void fixedHeightTest() {
        // TODO: test fixedHeight
    }

    /**
     * Test the property 'fixedHeightDownsampled'
     */
    @Test
    public void fixedHeightDownsampledTest() {
        // TODO: test fixedHeightDownsampled
    }

    /**
     * Test the property 'fixedHeightSmall'
     */
    @Test
    public void fixedHeightSmallTest() {
        // TODO: test fixedHeightSmall
    }

    /**
     * Test the property 'fixedHeightSmallStill'
     */
    @Test
    public void fixedHeightSmallStillTest() {
        // TODO: test fixedHeightSmallStill
    }

    /**
     * Test the property 'fixedHeightStill'
     */
    @Test
    public void fixedHeightStillTest() {
        // TODO: test fixedHeightStill
    }

    /**
     * Test the property 'fixedWidth'
     */
    @Test
    public void fixedWidthTest() {
        // TODO: test fixedWidth
    }

    /**
     * Test the property 'fixedWidthDownsampled'
     */
    @Test
    public void fixedWidthDownsampledTest() {
        // TODO: test fixedWidthDownsampled
    }

    /**
     * Test the property 'fixedWidthSmall'
     */
    @Test
    public void fixedWidthSmallTest() {
        // TODO: test fixedWidthSmall
    }

    /**
     * Test the property 'fixedWidthSmallStill'
     */
    @Test
    public void fixedWidthSmallStillTest() {
        // TODO: test fixedWidthSmallStill
    }

    /**
     * Test the property 'fixedWidthStill'
     */
    @Test
    public void fixedWidthStillTest() {
        // TODO: test fixedWidthStill
    }

    /**
     * Test the property 'looping'
     */
    @Test
    public void loopingTest() {
        // TODO: test looping
    }

    /**
     * Test the property 'original'
     */
    @Test
    public void originalTest() {
        // TODO: test original
    }

    /**
     * Test the property 'originalStill'
     */
    @Test
    public void originalStillTest() {
        // TODO: test originalStill
    }

    /**
     * Test the property 'preview'
     */
    @Test
    public void previewTest() {
        // TODO: test preview
    }

    /**
     * Test the property 'previewGif'
     */
    @Test
    public void previewGifTest() {
        // TODO: test previewGif
    }

}
