/*
 * Giphy API
 * Giphy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@giphy.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GifImagesDownsized;
import com.konfigthis.client.model.GifImagesDownsizedLarge;
import com.konfigthis.client.model.GifImagesDownsizedMedium;
import com.konfigthis.client.model.GifImagesDownsizedSmall;
import com.konfigthis.client.model.GifImagesDownsizedStill;
import com.konfigthis.client.model.GifImagesFixedHeight;
import com.konfigthis.client.model.GifImagesFixedHeightDownsampled;
import com.konfigthis.client.model.GifImagesFixedHeightSmall;
import com.konfigthis.client.model.GifImagesFixedHeightSmallStill;
import com.konfigthis.client.model.GifImagesFixedHeightStill;
import com.konfigthis.client.model.GifImagesFixedWidth;
import com.konfigthis.client.model.GifImagesFixedWidthDownsampled;
import com.konfigthis.client.model.GifImagesFixedWidthSmall;
import com.konfigthis.client.model.GifImagesFixedWidthSmallStill;
import com.konfigthis.client.model.GifImagesFixedWidthStill;
import com.konfigthis.client.model.GifImagesLooping;
import com.konfigthis.client.model.GifImagesOriginal;
import com.konfigthis.client.model.GifImagesOriginalStill;
import com.konfigthis.client.model.GifImagesPreview;
import com.konfigthis.client.model.GifImagesPreviewGif;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * An object containing data for various available formats and sizes of this GIF.
 */
@ApiModel(description = "An object containing data for various available formats and sizes of this GIF.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class GifImages {
  public static final String SERIALIZED_NAME_DOWNSIZED = "downsized";
  @SerializedName(SERIALIZED_NAME_DOWNSIZED)
  private GifImagesDownsized downsized;

  public static final String SERIALIZED_NAME_DOWNSIZED_LARGE = "downsized_large";
  @SerializedName(SERIALIZED_NAME_DOWNSIZED_LARGE)
  private GifImagesDownsizedLarge downsizedLarge;

  public static final String SERIALIZED_NAME_DOWNSIZED_MEDIUM = "downsized_medium";
  @SerializedName(SERIALIZED_NAME_DOWNSIZED_MEDIUM)
  private GifImagesDownsizedMedium downsizedMedium;

  public static final String SERIALIZED_NAME_DOWNSIZED_SMALL = "downsized_small";
  @SerializedName(SERIALIZED_NAME_DOWNSIZED_SMALL)
  private GifImagesDownsizedSmall downsizedSmall;

  public static final String SERIALIZED_NAME_DOWNSIZED_STILL = "downsized_still";
  @SerializedName(SERIALIZED_NAME_DOWNSIZED_STILL)
  private GifImagesDownsizedStill downsizedStill;

  public static final String SERIALIZED_NAME_FIXED_HEIGHT = "fixed_height";
  @SerializedName(SERIALIZED_NAME_FIXED_HEIGHT)
  private GifImagesFixedHeight fixedHeight;

  public static final String SERIALIZED_NAME_FIXED_HEIGHT_DOWNSAMPLED = "fixed_height_downsampled";
  @SerializedName(SERIALIZED_NAME_FIXED_HEIGHT_DOWNSAMPLED)
  private GifImagesFixedHeightDownsampled fixedHeightDownsampled;

  public static final String SERIALIZED_NAME_FIXED_HEIGHT_SMALL = "fixed_height_small";
  @SerializedName(SERIALIZED_NAME_FIXED_HEIGHT_SMALL)
  private GifImagesFixedHeightSmall fixedHeightSmall;

  public static final String SERIALIZED_NAME_FIXED_HEIGHT_SMALL_STILL = "fixed_height_small_still";
  @SerializedName(SERIALIZED_NAME_FIXED_HEIGHT_SMALL_STILL)
  private GifImagesFixedHeightSmallStill fixedHeightSmallStill;

  public static final String SERIALIZED_NAME_FIXED_HEIGHT_STILL = "fixed_height_still";
  @SerializedName(SERIALIZED_NAME_FIXED_HEIGHT_STILL)
  private GifImagesFixedHeightStill fixedHeightStill;

  public static final String SERIALIZED_NAME_FIXED_WIDTH = "fixed_width";
  @SerializedName(SERIALIZED_NAME_FIXED_WIDTH)
  private GifImagesFixedWidth fixedWidth;

  public static final String SERIALIZED_NAME_FIXED_WIDTH_DOWNSAMPLED = "fixed_width_downsampled";
  @SerializedName(SERIALIZED_NAME_FIXED_WIDTH_DOWNSAMPLED)
  private GifImagesFixedWidthDownsampled fixedWidthDownsampled;

  public static final String SERIALIZED_NAME_FIXED_WIDTH_SMALL = "fixed_width_small";
  @SerializedName(SERIALIZED_NAME_FIXED_WIDTH_SMALL)
  private GifImagesFixedWidthSmall fixedWidthSmall;

  public static final String SERIALIZED_NAME_FIXED_WIDTH_SMALL_STILL = "fixed_width_small_still";
  @SerializedName(SERIALIZED_NAME_FIXED_WIDTH_SMALL_STILL)
  private GifImagesFixedWidthSmallStill fixedWidthSmallStill;

  public static final String SERIALIZED_NAME_FIXED_WIDTH_STILL = "fixed_width_still";
  @SerializedName(SERIALIZED_NAME_FIXED_WIDTH_STILL)
  private GifImagesFixedWidthStill fixedWidthStill;

  public static final String SERIALIZED_NAME_LOOPING = "looping";
  @SerializedName(SERIALIZED_NAME_LOOPING)
  private GifImagesLooping looping;

  public static final String SERIALIZED_NAME_ORIGINAL = "original";
  @SerializedName(SERIALIZED_NAME_ORIGINAL)
  private GifImagesOriginal original;

  public static final String SERIALIZED_NAME_ORIGINAL_STILL = "original_still";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_STILL)
  private GifImagesOriginalStill originalStill;

  public static final String SERIALIZED_NAME_PREVIEW = "preview";
  @SerializedName(SERIALIZED_NAME_PREVIEW)
  private GifImagesPreview preview;

  public static final String SERIALIZED_NAME_PREVIEW_GIF = "preview_gif";
  @SerializedName(SERIALIZED_NAME_PREVIEW_GIF)
  private GifImagesPreviewGif previewGif;

  public GifImages() {
  }

  public GifImages downsized(GifImagesDownsized downsized) {
    
    
    
    
    this.downsized = downsized;
    return this;
  }

   /**
   * Get downsized
   * @return downsized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesDownsized getDownsized() {
    return downsized;
  }


  public void setDownsized(GifImagesDownsized downsized) {
    
    
    
    this.downsized = downsized;
  }


  public GifImages downsizedLarge(GifImagesDownsizedLarge downsizedLarge) {
    
    
    
    
    this.downsizedLarge = downsizedLarge;
    return this;
  }

   /**
   * Get downsizedLarge
   * @return downsizedLarge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesDownsizedLarge getDownsizedLarge() {
    return downsizedLarge;
  }


  public void setDownsizedLarge(GifImagesDownsizedLarge downsizedLarge) {
    
    
    
    this.downsizedLarge = downsizedLarge;
  }


  public GifImages downsizedMedium(GifImagesDownsizedMedium downsizedMedium) {
    
    
    
    
    this.downsizedMedium = downsizedMedium;
    return this;
  }

   /**
   * Get downsizedMedium
   * @return downsizedMedium
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesDownsizedMedium getDownsizedMedium() {
    return downsizedMedium;
  }


  public void setDownsizedMedium(GifImagesDownsizedMedium downsizedMedium) {
    
    
    
    this.downsizedMedium = downsizedMedium;
  }


  public GifImages downsizedSmall(GifImagesDownsizedSmall downsizedSmall) {
    
    
    
    
    this.downsizedSmall = downsizedSmall;
    return this;
  }

   /**
   * Get downsizedSmall
   * @return downsizedSmall
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesDownsizedSmall getDownsizedSmall() {
    return downsizedSmall;
  }


  public void setDownsizedSmall(GifImagesDownsizedSmall downsizedSmall) {
    
    
    
    this.downsizedSmall = downsizedSmall;
  }


  public GifImages downsizedStill(GifImagesDownsizedStill downsizedStill) {
    
    
    
    
    this.downsizedStill = downsizedStill;
    return this;
  }

   /**
   * Get downsizedStill
   * @return downsizedStill
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesDownsizedStill getDownsizedStill() {
    return downsizedStill;
  }


  public void setDownsizedStill(GifImagesDownsizedStill downsizedStill) {
    
    
    
    this.downsizedStill = downsizedStill;
  }


  public GifImages fixedHeight(GifImagesFixedHeight fixedHeight) {
    
    
    
    
    this.fixedHeight = fixedHeight;
    return this;
  }

   /**
   * Get fixedHeight
   * @return fixedHeight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesFixedHeight getFixedHeight() {
    return fixedHeight;
  }


  public void setFixedHeight(GifImagesFixedHeight fixedHeight) {
    
    
    
    this.fixedHeight = fixedHeight;
  }


  public GifImages fixedHeightDownsampled(GifImagesFixedHeightDownsampled fixedHeightDownsampled) {
    
    
    
    
    this.fixedHeightDownsampled = fixedHeightDownsampled;
    return this;
  }

   /**
   * Get fixedHeightDownsampled
   * @return fixedHeightDownsampled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesFixedHeightDownsampled getFixedHeightDownsampled() {
    return fixedHeightDownsampled;
  }


  public void setFixedHeightDownsampled(GifImagesFixedHeightDownsampled fixedHeightDownsampled) {
    
    
    
    this.fixedHeightDownsampled = fixedHeightDownsampled;
  }


  public GifImages fixedHeightSmall(GifImagesFixedHeightSmall fixedHeightSmall) {
    
    
    
    
    this.fixedHeightSmall = fixedHeightSmall;
    return this;
  }

   /**
   * Get fixedHeightSmall
   * @return fixedHeightSmall
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesFixedHeightSmall getFixedHeightSmall() {
    return fixedHeightSmall;
  }


  public void setFixedHeightSmall(GifImagesFixedHeightSmall fixedHeightSmall) {
    
    
    
    this.fixedHeightSmall = fixedHeightSmall;
  }


  public GifImages fixedHeightSmallStill(GifImagesFixedHeightSmallStill fixedHeightSmallStill) {
    
    
    
    
    this.fixedHeightSmallStill = fixedHeightSmallStill;
    return this;
  }

   /**
   * Get fixedHeightSmallStill
   * @return fixedHeightSmallStill
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesFixedHeightSmallStill getFixedHeightSmallStill() {
    return fixedHeightSmallStill;
  }


  public void setFixedHeightSmallStill(GifImagesFixedHeightSmallStill fixedHeightSmallStill) {
    
    
    
    this.fixedHeightSmallStill = fixedHeightSmallStill;
  }


  public GifImages fixedHeightStill(GifImagesFixedHeightStill fixedHeightStill) {
    
    
    
    
    this.fixedHeightStill = fixedHeightStill;
    return this;
  }

   /**
   * Get fixedHeightStill
   * @return fixedHeightStill
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesFixedHeightStill getFixedHeightStill() {
    return fixedHeightStill;
  }


  public void setFixedHeightStill(GifImagesFixedHeightStill fixedHeightStill) {
    
    
    
    this.fixedHeightStill = fixedHeightStill;
  }


  public GifImages fixedWidth(GifImagesFixedWidth fixedWidth) {
    
    
    
    
    this.fixedWidth = fixedWidth;
    return this;
  }

   /**
   * Get fixedWidth
   * @return fixedWidth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesFixedWidth getFixedWidth() {
    return fixedWidth;
  }


  public void setFixedWidth(GifImagesFixedWidth fixedWidth) {
    
    
    
    this.fixedWidth = fixedWidth;
  }


  public GifImages fixedWidthDownsampled(GifImagesFixedWidthDownsampled fixedWidthDownsampled) {
    
    
    
    
    this.fixedWidthDownsampled = fixedWidthDownsampled;
    return this;
  }

   /**
   * Get fixedWidthDownsampled
   * @return fixedWidthDownsampled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesFixedWidthDownsampled getFixedWidthDownsampled() {
    return fixedWidthDownsampled;
  }


  public void setFixedWidthDownsampled(GifImagesFixedWidthDownsampled fixedWidthDownsampled) {
    
    
    
    this.fixedWidthDownsampled = fixedWidthDownsampled;
  }


  public GifImages fixedWidthSmall(GifImagesFixedWidthSmall fixedWidthSmall) {
    
    
    
    
    this.fixedWidthSmall = fixedWidthSmall;
    return this;
  }

   /**
   * Get fixedWidthSmall
   * @return fixedWidthSmall
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesFixedWidthSmall getFixedWidthSmall() {
    return fixedWidthSmall;
  }


  public void setFixedWidthSmall(GifImagesFixedWidthSmall fixedWidthSmall) {
    
    
    
    this.fixedWidthSmall = fixedWidthSmall;
  }


  public GifImages fixedWidthSmallStill(GifImagesFixedWidthSmallStill fixedWidthSmallStill) {
    
    
    
    
    this.fixedWidthSmallStill = fixedWidthSmallStill;
    return this;
  }

   /**
   * Get fixedWidthSmallStill
   * @return fixedWidthSmallStill
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesFixedWidthSmallStill getFixedWidthSmallStill() {
    return fixedWidthSmallStill;
  }


  public void setFixedWidthSmallStill(GifImagesFixedWidthSmallStill fixedWidthSmallStill) {
    
    
    
    this.fixedWidthSmallStill = fixedWidthSmallStill;
  }


  public GifImages fixedWidthStill(GifImagesFixedWidthStill fixedWidthStill) {
    
    
    
    
    this.fixedWidthStill = fixedWidthStill;
    return this;
  }

   /**
   * Get fixedWidthStill
   * @return fixedWidthStill
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesFixedWidthStill getFixedWidthStill() {
    return fixedWidthStill;
  }


  public void setFixedWidthStill(GifImagesFixedWidthStill fixedWidthStill) {
    
    
    
    this.fixedWidthStill = fixedWidthStill;
  }


  public GifImages looping(GifImagesLooping looping) {
    
    
    
    
    this.looping = looping;
    return this;
  }

   /**
   * Get looping
   * @return looping
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesLooping getLooping() {
    return looping;
  }


  public void setLooping(GifImagesLooping looping) {
    
    
    
    this.looping = looping;
  }


  public GifImages original(GifImagesOriginal original) {
    
    
    
    
    this.original = original;
    return this;
  }

   /**
   * Get original
   * @return original
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesOriginal getOriginal() {
    return original;
  }


  public void setOriginal(GifImagesOriginal original) {
    
    
    
    this.original = original;
  }


  public GifImages originalStill(GifImagesOriginalStill originalStill) {
    
    
    
    
    this.originalStill = originalStill;
    return this;
  }

   /**
   * Get originalStill
   * @return originalStill
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesOriginalStill getOriginalStill() {
    return originalStill;
  }


  public void setOriginalStill(GifImagesOriginalStill originalStill) {
    
    
    
    this.originalStill = originalStill;
  }


  public GifImages preview(GifImagesPreview preview) {
    
    
    
    
    this.preview = preview;
    return this;
  }

   /**
   * Get preview
   * @return preview
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesPreview getPreview() {
    return preview;
  }


  public void setPreview(GifImagesPreview preview) {
    
    
    
    this.preview = preview;
  }


  public GifImages previewGif(GifImagesPreviewGif previewGif) {
    
    
    
    
    this.previewGif = previewGif;
    return this;
  }

   /**
   * Get previewGif
   * @return previewGif
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GifImagesPreviewGif getPreviewGif() {
    return previewGif;
  }


  public void setPreviewGif(GifImagesPreviewGif previewGif) {
    
    
    
    this.previewGif = previewGif;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GifImages instance itself
   */
  public GifImages putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GifImages gifImages = (GifImages) o;
    return Objects.equals(this.downsized, gifImages.downsized) &&
        Objects.equals(this.downsizedLarge, gifImages.downsizedLarge) &&
        Objects.equals(this.downsizedMedium, gifImages.downsizedMedium) &&
        Objects.equals(this.downsizedSmall, gifImages.downsizedSmall) &&
        Objects.equals(this.downsizedStill, gifImages.downsizedStill) &&
        Objects.equals(this.fixedHeight, gifImages.fixedHeight) &&
        Objects.equals(this.fixedHeightDownsampled, gifImages.fixedHeightDownsampled) &&
        Objects.equals(this.fixedHeightSmall, gifImages.fixedHeightSmall) &&
        Objects.equals(this.fixedHeightSmallStill, gifImages.fixedHeightSmallStill) &&
        Objects.equals(this.fixedHeightStill, gifImages.fixedHeightStill) &&
        Objects.equals(this.fixedWidth, gifImages.fixedWidth) &&
        Objects.equals(this.fixedWidthDownsampled, gifImages.fixedWidthDownsampled) &&
        Objects.equals(this.fixedWidthSmall, gifImages.fixedWidthSmall) &&
        Objects.equals(this.fixedWidthSmallStill, gifImages.fixedWidthSmallStill) &&
        Objects.equals(this.fixedWidthStill, gifImages.fixedWidthStill) &&
        Objects.equals(this.looping, gifImages.looping) &&
        Objects.equals(this.original, gifImages.original) &&
        Objects.equals(this.originalStill, gifImages.originalStill) &&
        Objects.equals(this.preview, gifImages.preview) &&
        Objects.equals(this.previewGif, gifImages.previewGif)&&
        Objects.equals(this.additionalProperties, gifImages.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(downsized, downsizedLarge, downsizedMedium, downsizedSmall, downsizedStill, fixedHeight, fixedHeightDownsampled, fixedHeightSmall, fixedHeightSmallStill, fixedHeightStill, fixedWidth, fixedWidthDownsampled, fixedWidthSmall, fixedWidthSmallStill, fixedWidthStill, looping, original, originalStill, preview, previewGif, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GifImages {\n");
    sb.append("    downsized: ").append(toIndentedString(downsized)).append("\n");
    sb.append("    downsizedLarge: ").append(toIndentedString(downsizedLarge)).append("\n");
    sb.append("    downsizedMedium: ").append(toIndentedString(downsizedMedium)).append("\n");
    sb.append("    downsizedSmall: ").append(toIndentedString(downsizedSmall)).append("\n");
    sb.append("    downsizedStill: ").append(toIndentedString(downsizedStill)).append("\n");
    sb.append("    fixedHeight: ").append(toIndentedString(fixedHeight)).append("\n");
    sb.append("    fixedHeightDownsampled: ").append(toIndentedString(fixedHeightDownsampled)).append("\n");
    sb.append("    fixedHeightSmall: ").append(toIndentedString(fixedHeightSmall)).append("\n");
    sb.append("    fixedHeightSmallStill: ").append(toIndentedString(fixedHeightSmallStill)).append("\n");
    sb.append("    fixedHeightStill: ").append(toIndentedString(fixedHeightStill)).append("\n");
    sb.append("    fixedWidth: ").append(toIndentedString(fixedWidth)).append("\n");
    sb.append("    fixedWidthDownsampled: ").append(toIndentedString(fixedWidthDownsampled)).append("\n");
    sb.append("    fixedWidthSmall: ").append(toIndentedString(fixedWidthSmall)).append("\n");
    sb.append("    fixedWidthSmallStill: ").append(toIndentedString(fixedWidthSmallStill)).append("\n");
    sb.append("    fixedWidthStill: ").append(toIndentedString(fixedWidthStill)).append("\n");
    sb.append("    looping: ").append(toIndentedString(looping)).append("\n");
    sb.append("    original: ").append(toIndentedString(original)).append("\n");
    sb.append("    originalStill: ").append(toIndentedString(originalStill)).append("\n");
    sb.append("    preview: ").append(toIndentedString(preview)).append("\n");
    sb.append("    previewGif: ").append(toIndentedString(previewGif)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("downsized");
    openapiFields.add("downsized_large");
    openapiFields.add("downsized_medium");
    openapiFields.add("downsized_small");
    openapiFields.add("downsized_still");
    openapiFields.add("fixed_height");
    openapiFields.add("fixed_height_downsampled");
    openapiFields.add("fixed_height_small");
    openapiFields.add("fixed_height_small_still");
    openapiFields.add("fixed_height_still");
    openapiFields.add("fixed_width");
    openapiFields.add("fixed_width_downsampled");
    openapiFields.add("fixed_width_small");
    openapiFields.add("fixed_width_small_still");
    openapiFields.add("fixed_width_still");
    openapiFields.add("looping");
    openapiFields.add("original");
    openapiFields.add("original_still");
    openapiFields.add("preview");
    openapiFields.add("preview_gif");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GifImages
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GifImages.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GifImages is not found in the empty JSON string", GifImages.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `downsized`
      if (jsonObj.get("downsized") != null && !jsonObj.get("downsized").isJsonNull()) {
        GifImagesDownsized.validateJsonObject(jsonObj.getAsJsonObject("downsized"));
      }
      // validate the optional field `downsized_large`
      if (jsonObj.get("downsized_large") != null && !jsonObj.get("downsized_large").isJsonNull()) {
        GifImagesDownsizedLarge.validateJsonObject(jsonObj.getAsJsonObject("downsized_large"));
      }
      // validate the optional field `downsized_medium`
      if (jsonObj.get("downsized_medium") != null && !jsonObj.get("downsized_medium").isJsonNull()) {
        GifImagesDownsizedMedium.validateJsonObject(jsonObj.getAsJsonObject("downsized_medium"));
      }
      // validate the optional field `downsized_small`
      if (jsonObj.get("downsized_small") != null && !jsonObj.get("downsized_small").isJsonNull()) {
        GifImagesDownsizedSmall.validateJsonObject(jsonObj.getAsJsonObject("downsized_small"));
      }
      // validate the optional field `downsized_still`
      if (jsonObj.get("downsized_still") != null && !jsonObj.get("downsized_still").isJsonNull()) {
        GifImagesDownsizedStill.validateJsonObject(jsonObj.getAsJsonObject("downsized_still"));
      }
      // validate the optional field `fixed_height`
      if (jsonObj.get("fixed_height") != null && !jsonObj.get("fixed_height").isJsonNull()) {
        GifImagesFixedHeight.validateJsonObject(jsonObj.getAsJsonObject("fixed_height"));
      }
      // validate the optional field `fixed_height_downsampled`
      if (jsonObj.get("fixed_height_downsampled") != null && !jsonObj.get("fixed_height_downsampled").isJsonNull()) {
        GifImagesFixedHeightDownsampled.validateJsonObject(jsonObj.getAsJsonObject("fixed_height_downsampled"));
      }
      // validate the optional field `fixed_height_small`
      if (jsonObj.get("fixed_height_small") != null && !jsonObj.get("fixed_height_small").isJsonNull()) {
        GifImagesFixedHeightSmall.validateJsonObject(jsonObj.getAsJsonObject("fixed_height_small"));
      }
      // validate the optional field `fixed_height_small_still`
      if (jsonObj.get("fixed_height_small_still") != null && !jsonObj.get("fixed_height_small_still").isJsonNull()) {
        GifImagesFixedHeightSmallStill.validateJsonObject(jsonObj.getAsJsonObject("fixed_height_small_still"));
      }
      // validate the optional field `fixed_height_still`
      if (jsonObj.get("fixed_height_still") != null && !jsonObj.get("fixed_height_still").isJsonNull()) {
        GifImagesFixedHeightStill.validateJsonObject(jsonObj.getAsJsonObject("fixed_height_still"));
      }
      // validate the optional field `fixed_width`
      if (jsonObj.get("fixed_width") != null && !jsonObj.get("fixed_width").isJsonNull()) {
        GifImagesFixedWidth.validateJsonObject(jsonObj.getAsJsonObject("fixed_width"));
      }
      // validate the optional field `fixed_width_downsampled`
      if (jsonObj.get("fixed_width_downsampled") != null && !jsonObj.get("fixed_width_downsampled").isJsonNull()) {
        GifImagesFixedWidthDownsampled.validateJsonObject(jsonObj.getAsJsonObject("fixed_width_downsampled"));
      }
      // validate the optional field `fixed_width_small`
      if (jsonObj.get("fixed_width_small") != null && !jsonObj.get("fixed_width_small").isJsonNull()) {
        GifImagesFixedWidthSmall.validateJsonObject(jsonObj.getAsJsonObject("fixed_width_small"));
      }
      // validate the optional field `fixed_width_small_still`
      if (jsonObj.get("fixed_width_small_still") != null && !jsonObj.get("fixed_width_small_still").isJsonNull()) {
        GifImagesFixedWidthSmallStill.validateJsonObject(jsonObj.getAsJsonObject("fixed_width_small_still"));
      }
      // validate the optional field `fixed_width_still`
      if (jsonObj.get("fixed_width_still") != null && !jsonObj.get("fixed_width_still").isJsonNull()) {
        GifImagesFixedWidthStill.validateJsonObject(jsonObj.getAsJsonObject("fixed_width_still"));
      }
      // validate the optional field `looping`
      if (jsonObj.get("looping") != null && !jsonObj.get("looping").isJsonNull()) {
        GifImagesLooping.validateJsonObject(jsonObj.getAsJsonObject("looping"));
      }
      // validate the optional field `original`
      if (jsonObj.get("original") != null && !jsonObj.get("original").isJsonNull()) {
        GifImagesOriginal.validateJsonObject(jsonObj.getAsJsonObject("original"));
      }
      // validate the optional field `original_still`
      if (jsonObj.get("original_still") != null && !jsonObj.get("original_still").isJsonNull()) {
        GifImagesOriginalStill.validateJsonObject(jsonObj.getAsJsonObject("original_still"));
      }
      // validate the optional field `preview`
      if (jsonObj.get("preview") != null && !jsonObj.get("preview").isJsonNull()) {
        GifImagesPreview.validateJsonObject(jsonObj.getAsJsonObject("preview"));
      }
      // validate the optional field `preview_gif`
      if (jsonObj.get("preview_gif") != null && !jsonObj.get("preview_gif").isJsonNull()) {
        GifImagesPreviewGif.validateJsonObject(jsonObj.getAsJsonObject("preview_gif"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GifImages.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GifImages' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GifImages> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GifImages.class));

       return (TypeAdapter<T>) new TypeAdapter<GifImages>() {
           @Override
           public void write(JsonWriter out, GifImages value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GifImages read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             GifImages instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GifImages given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GifImages
  * @throws IOException if the JSON string is invalid with respect to GifImages
  */
  public static GifImages fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GifImages.class);
  }

 /**
  * Convert an instance of GifImages to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

