/*
 * Giphy API
 * Giphy API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@giphy.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.GifsGetByIdResponse;
import com.konfigthis.client.model.GifsGetByIdsResponse;
import com.konfigthis.client.model.GifsGetRandomGifResponse;
import com.konfigthis.client.model.GifsGetTrendingGifsResponse;
import com.konfigthis.client.model.GifsSearchGifsResponse;
import com.konfigthis.client.model.GifsTranslatePhraseGifResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GifsApi
 */
@Disabled
public class GifsApiTest {

    private static GifsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new GifsApi(apiClient);
    }

    /**
     * Get GIF by Id
     *
     * Returns a GIF given that GIF&#39;s unique ID 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        Integer gifId = null;
        GifsGetByIdResponse response = api.getById(gifId)
                .execute();
        // TODO: test validations
    }

    /**
     * Get GIFs by ID
     *
     * A multiget version of the get GIF by ID endpoint. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdsTest() throws ApiException {
        String ids = null;
        GifsGetByIdsResponse response = api.getByIds()
                .ids(ids)
                .execute();
        // TODO: test validations
    }

    /**
     * Random GIF
     *
     * Returns a random GIF, limited by tag. Excluding the tag parameter will return a random GIF from the GIPHY catalog. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRandomGifTest() throws ApiException {
        String tag = null;
        String rating = null;
        GifsGetRandomGifResponse response = api.getRandomGif()
                .tag(tag)
                .rating(rating)
                .execute();
        // TODO: test validations
    }

    /**
     * Trending GIFs
     *
     * Fetch GIFs currently trending online. Hand curated by the GIPHY editorial team.  The data returned mirrors the GIFs showcased on the GIPHY homepage. Returns 25 results by default. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTrendingGifsTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String rating = null;
        GifsGetTrendingGifsResponse response = api.getTrendingGifs()
                .limit(limit)
                .offset(offset)
                .rating(rating)
                .execute();
        // TODO: test validations
    }

    /**
     * Search GIFs
     *
     * Search all GIPHY GIFs for a word or phrase. Punctuation will be stripped and ignored.  Use a plus or url encode for phrases. Example paul+rudd, ryan+gosling or american+psycho. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchGifsTest() throws ApiException {
        String q = null;
        Integer limit = null;
        Integer offset = null;
        String rating = null;
        String lang = null;
        GifsSearchGifsResponse response = api.searchGifs(q)
                .limit(limit)
                .offset(offset)
                .rating(rating)
                .lang(lang)
                .execute();
        // TODO: test validations
    }

    /**
     * Translate phrase to GIF
     *
     * The translate API draws on search, but uses the GIPHY &#x60;special sauce&#x60; to handle translating from one vocabulary to another. In this case, words and phrases to GIF 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void translatePhraseGifTest() throws ApiException {
        String s = null;
        GifsTranslatePhraseGifResponse response = api.translatePhraseGif(s)
                .execute();
        // TODO: test validations
    }

}
